More BL-7 upgrade changes.
Now we can enable site without it crashing.

Fixed the following errors:

1. undefined methods:
     - add_show_tools_partial

2. undefined variables:
     - Blacklight::SavedSearches
     - Blacklight::RequestBuilders
     - include Blacklight::SearchHelper

4. couldn't find file 'blacklight/core' with type 'application/javascript'
5. couldn't find file 'bootstrap/tooltip' with type 'application/javascript'
6. Undefined mixin 'sr-only'.
7. undefined method `suggest_index_path' for #<ActionDispatch::Routing::RoutesProxy:0x007feef40ca720>`
8. Missing partial shared/_ajax_modal
9. blacklight_range_limit: undefined local variable or method `solr_field`
10. undefined local variable or method `spell_check_max' `
11. No route matches {:action=>"suggest", :controller=>"search"}
12. undefined method `custom_data' for nil:NilClass`
13. {:exception=>#<NoMethodError: undefined method `search_results' for #<BentoSearch::BooksEngine:0x007f901dc108b8>>`}
14. Sorry! An error occured and results could not be retrieved.

{:exception=>#<ArgumentError: wrong number of arguments (given 1, expected 0)>}: app/search_engines/bento_search/books_engine.rb:9:in `search_implementation'

15. undefined local variable or method `sort_fields'`
16. No route matches {:action=>"index", :controller=>"catalog"}
17. undefined local variable or method `repository' `

TODO:

* primo links not working (they work from bento)
* facets not showing up on catalog/primo (they show up in bento)
* enabling bookmarks breaks primo and bento